### ISSUE TITLE
License

### ISSUE THREAD

**Issue by loren138** [nickmccurdy/vite-react-testing#11]
Hi!

Thanks for making some Vite templates. Would you consider adding a license to these repos?
As is, I wouldn't want to use them in software (especially commercial) due to potential licensing issues.

**Comment by nickmccurdy** [comment]
I intentionally excluded a license file because this repository is a template, and I don't want users to always opted into a license for their derivative projects. There's a slightly more in depth explanation in Vite's issues: https://github.com/vitejs/vite/issues/5034

Note that since this repository is on GitHub and I've agreed to its TOS, anyone on GitHub is free to read, fork, and use the template.

**Comment by loren138** [comment]
Hm, I agree with the assessment that created repos should not have a license by default (so the new developer can make their own choice).
I also agree with their assessment that https://github.com/vitejs/vite/blob/main/LICENSE applies to the sub package https://github.com/vitejs/vite/tree/main/packages/create-vite/template-react (and being MIT doesn't require that users of the template also license as MIT)

CRA is/was similar with https://github.com/facebook/create-react-app/blob/main/LICENSE applying to https://github.com/facebook/create-react-app/tree/main/packages/cra-template

This creates a bit of a problem for template repos like yours where there isn't a higher level directory where you could put the license for the template files.

That said, my current work needs an explicit license file, so I may start from the create-vite-template instead.

**Comment by nickmccurdy** [comment]
It's also why I've avoided setting up CI and package locks for now. Hopefully the DX around templates will improve in the future, but for now I'd rather deal with this to keep it easy to get started.

Is this derivative repository you want to make for work going to be public on GitHub or internal?

**Comment by loren138** [comment]
That's fair. It's internal.

**Comment by nickmccurdy** [comment]
In that case, feel free to do what you want with this. If you need to include licensing information in the repository or product, you can optionally attribute me as part of it.
